# Generated by Django 4.2.7 on 2024-01-20 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_remove_employee_in_time_remove_employee_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
