# Generated by Django 4.2.7 on 2024-01-23 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='emp_date',
            field=models.DateField(default=datetime.date(2024, 1, 23)),
        ),
    ]
